### ISSUE TITLE
[Question/Feature request] Aliasing token / cross referencing

### ISSUE THREAD

**Issue by b-barry** [lukasoppermann/design-tokens#125]
Hello,

Thanks for this excellent plugin. It will make our process faster.
I am wondering if this plugin supports alias between token.
I am following the recommendation of [Abobe spectrum](https://spectrum.adobe.com/page/design-tokens/#Design-token-types).

Thanks in advance!

**Comment by lukasoppermann** [comment]
Hey @b-barry this is a topic I find very interesting as well.

Do you have an idea how aliases could be defined within figma?

**Comment by janina3** [comment]
I am also interested in alias support. I'm relatively new to Figma (just switched from XD) and new to tokens in general, so don't have an idea on how to go about this yet

**Comment by b-barry** [comment]
I am testing another plugin to analyse how they are doing it. I think it will be complex

**Comment by lukasoppermann** [comment]
Hey, @b-barry that is true. I see a view problems that need to be solved:

1. How does the plugin know a token is a references? (Name, portion of the name, ref in the description (=> only works for styles))
2. Would the user expect the references to update or only work on the export?
Problems: if it does not update, you may use two different colors (as you changed one that is referenced) and than export them where they will be changed to be the same color
Otherwise how will the plugin update the references it, you would need to be called to update. Which is an annoying workflow, but probably the best

**Comment by lukasoppermann** [comment]
Hey @toiletgranny I agree that using a reference comment is the only valid solution. However I would prefer a simple `alias: {colors.primary}` or maybe even `alias: colors/primary`

I think to begin with adding support for colors would be good.

Are you interested in tackling this?
