### ISSUE TITLE
The Save & Export is not working any longer

### ISSUE THREAD

**Issue by fitfab** [lukasoppermann/design-tokens#172]
<img width="661" alt="Screen Shot 2022-01-05 at 3 53 47 PM" src="https://user-images.githubusercontent.com/286703/148287924-ef8cd011-864e-496f-aaae-d41f4b46d74f.png">

When one clicks on the `Save & Export`, the error below shows up in the console:

<img width="1365" alt="Screen Shot 2022-01-05 at 3 56 25 PM" src="https://user-images.githubusercontent.com/286703/148288267-6e902329-fb81-472b-8350-5a607b2e24eb.png">

**Comment by lukasoppermann** [comment]
Thanks will look into it.

**Comment by lukasoppermann** [comment]
Hey, I had a look and can not reproduce the error on my side. From the screenshot I am assuming you use the "Send to Url" command, correct?

Does it arrive at the server? Is it possible that you get an error back?
Did you try to reset the settings with the reset settings command?

Can you otherwise share all the details (excluding your personal access token)

**Comment by fitfab** [comment]
Actually we figure it out.
We had to check the `add token type to name of the token`
Thank you for you prompt response.
<img width="672" alt="Screen Shot 2022-01-06 at 12 42 37 PM" src="https://user-images.githubusercontent.com/286703/148426743-d23d3781-9297-4d71-ab14-8f7e1f6fdae9.png">
