### ISSUE TITLE
Unable to push tokens to a custom server

### ISSUE THREAD

**Issue by 12pixels** [lukasoppermann/design-tokens#186]
Hey Lukas,
I get the same error message from the plugin asking me to "...check settings and server" when I push the tokens to my dev url - https://12pixels.glitch.me/commit-tokens
My server script only accepts the json packet and pushes it to my console. There is nothing more going on there. The CORS header is set and I'm using your demo Figma file.

**Comment by lukasoppermann** [comment]
Hey, I am not familiar with glitch. This means that you got an error from the server.
You can open the developer console in figma to inspect the error to get more details. 
I can't tell you what the issue is, but if you figure it out (or at least get the details from the console) I may be able to ehelp.

**Comment by 12pixels** [comment]
Operating the figma plugin from the browser helped much. I hadn't thought of that.
Thanks, Lukas
