### ISSUE TITLE
Persistent 422 Error

### ISSUE THREAD

**Issue by klafin91** [lukasoppermann/design-tokens#240]
Our team has been having an issue with exporting tokens to our github token library. We've generated new github access tokens and that hasn't changed anything. Any tips on how to alleviate this issue or this is a bug? Response message says "client payload is too large" but the exported json file is only around 77kb.

Fetched file is pasted below as well

![image](https://user-images.githubusercontent.com/83669802/217945779-b824be96-ef67-4497-85cb-f466c593c4c0.png)

![image](https://user-images.githubusercontent.com/83669802/217943954-a0fcc570-d2e3-49b0-8dee-6ced6c223390.png)

[Fetch.txt](https://github.com/lukasoppermann/design-tokens/files/10701757/Fetch.txt)

**Comment by lukasoppermann** [comment]
The problem is that [50kb is the max](https://github.com/lukasoppermann/design-tokens/issues/155#issuecomment-975495873) for dispatches.

I am not an actions expert, maybe there is a different way like sending the data to a bitbucket and letting this trigger github?

I am happy to help with this, but I have no solution at hand, so if you have an idea, let me know.

**Comment by lukasoppermann** [comment]
There is now another option to remove `$extension` property which may help.
