### ISSUE TITLE
Remove calculation for lineHeight

### ISSUE THREAD

**Issue by dj-kmuldoon** [lukasoppermann/design-tokens#243]
This is very good for css/scss but not useful for Android and iOS.

`"lineHeight": "1.2",`

Please maintain previous output which matched the px dimension in Figma.

**Comment by lukasoppermann** [comment]
Hey @dj-kmuldoon I understand that this may be inconvenient for you.

The reason I made this change is that this is required to be `w3c` compatible: https://tr.designtokens.org/format/#typography

> lineHeight: The vertical spacing between lines of typography. The value of this property MUST be a valid [number value](https://tr.designtokens.org/format/#number) or a reference to a number token. **The number SHOULD be interpreted as a multiplier of the fontSize.**

However you should be able to easily convert the number back using a transformer for android, since the token would be a combined one in any case.

All you would need to do is multiply the `fontySize` with the `lineHeight`.

If you use this transformer: https://github.com/lukasoppermann/design-tokens/blob/main/examples/libs/android/formatFontStyle.js

See this line: `<item name="android:lineHeight">${compositeToken.value.lineHeight * compositeToken.value.fontSize}sp</item>\n`

```js
const { fileHeader } = require('style-dictionary').formatHelpers
const camelCase = require('../common/camelCaseHelper')

const letterSpacingToFloat = (letterSpacing, fontSize) => 1 + (letterSpacing / fontSize)

const printDescription = description => (description && description !== '' && description !== null ? `    <!-- ${description} -->\n` : '')

module.exports = ({ dictionary, platform, options = {}, file }) => {
  const fontStyles = dictionary.allTokens
    // remove underlined
    .filter(compositeToken => compositeToken.original.value.textDecoration !== 'underline')
    // create style
    .map(compositeToken => {
      return `  <style name="${camelCase(compositeToken.name)}">\n` +
      printDescription(compositeToken.description) +
    `    <item name="android:fontFamily">${options.fontFamilies[compositeToken.original.value.fontFamily]}</item>\n` +
    `    <item name="android:textSize">@dimen/${compositeToken.name}</item>\n` +
    `    <item name="android:lineHeight">${compositeToken.value.lineHeight * compositeToken.value.fontSize}sp</item>\n` +
    `    <item name="android:letterSpacing">${letterSpacingToFloat(compositeToken.original.value.letterSpacing, compositeToken.original.value.fontSize)}</item>\n` +
    `    <item name="fontStyle">${compositeToken.original.value.fontStyle}</item>\n` +
    `    <item name="fontWeight">${compositeToken.original.value.fontWeight}</item>\n` +
    '  </style>\n'
    })
  return (
    '<?xml version="1.0" encoding="utf-8"?>\n' +
      fileHeader({ file, commentStyle: 'xml' }) +
      '\n<resources>\n' +
        fontStyles.join('\n') +
      '\n</resources>\n'
  )
}
```

**Comment by caoimghgin** [comment]
Then again, I suppose I do convert to a multiplier of the fontSize for CSS anyway. Sure, I'll just reverse my thought process. Thanks for responding, and feel free to close this ticket as resolved.

**Comment by lukasoppermann** [comment]
Great, thanks for understanding.
