### ISSUE TITLE
Settings: enable category prefix (e.g. color or typography)

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/design-tokens#31]
Allow user to enable top level categories.
E.g. all colors are clustered below `colors`

**Comment by lucianomlima** [comment]
Hi, thanks for this awesome library.

Is this issue related to how style dictionary matches color transform?
I realize that colors are exported with fill category but in style dictionary should be color, because it uses [this util function](https://github.com/amzn/style-dictionary/blob/29e511d07e7991430f6f892879aeb0ade0c6a289/lib/common/transforms.js#L20-L22):
```js
function isColor(token) {
  return token.attributes.category === 'color';
}
```

Right now, no color transforms works because it uses fill as a category.

**Comment by lukasoppermann** [comment]
In parts. So you could solve it by naming your colors `color/red` and disabled the `category prefix` (e.g. fill).

Style dictionary does not deal with gradients specifically, do they?

You can solve this issue now, by writing a custom function and look for category === 'fill' but I appreciate it would be neat to work out of the box.

However this is going to be a breaking change, so I will need to add it carefully. Are there other issues with style dictionary or just colors?

**Comment by lucianomlima** [comment]
Thanks @lukasoppermann. Change to `color` solved!
About gradients, I don't know, yet. But I try to figure out.

> However this is going to be a breaking change, so I will need to add it carefully. Are there other issues with style dictionary or just colors?

If I found any issues, I open an issue here! 😉
