### ISSUE TITLE
Sending tokens to Github repo

### ISSUE THREAD

**Issue by usethetics** [lukasoppermann/design-tokens#44]
I’m trying to push tokens to a Github repo.

I have created a repo, added the Server URL for that repo (in *https://api.github.com/repo/:username/:repo* format) and Access token. Upon sending my design tokens I receive a confirmation ‘Design tokens pushed to server!’, however I do not see any update in my repo.

The local exported file looks fine.

**Comment by lukasoppermann** [comment]
Hey @usethetics,

since this issue came up before, one quick question, did you go into the "Actions" tab in your repo and click the green "enable actions" button? (https://github.com/lukasoppermann/design-token-transformer#transformation-in-github-repository)

Sadly, if this is not enabled github swallows the push without returning any error.

**Comment by usethetics** [comment]
Hi @lukasoppermann, if I go into the Actions tab I get the ‘Get started with GitHub Actions’ overview page without an ‘enable actions’ button.

**Comment by lukasoppermann** [comment]
Okay, but you did **fork** this repository https://github.com/lukasoppermann/design-token-transformer correct? (You did not just create a new one, correct?)

If you did create a fork and still can't enable it, I'll have to check it later. Did you use actions on github before?

**Comment by usethetics** [comment]
Sorry, I should’ve been clearer. I tried both creating a new project and forking design-token-transformer.

In the forked project I now have enabled actions and followed the steps outlined. The package.json has been updated to reflect the correct repository URL. 

TBH, I haven’t used Github Actions before but I take it the correct actions are forked over right? Do I need to update anything in the transform-tokens.yml?

On the Figma side; is this server URL correct? https://api.github.com/repo/usethetics/design-token-transformer.git

**Comment by lukasoppermann** [comment]
Hey @usethetics, correct, the action file is included in the project, so when you create a fork it will be present.

The url has to be updated though, the correct one would be:
Not that you are missing an **s** in repo**s** and need to update the end (remove `.git` and add `/dispatches`).

```
https://api.github.com/repos/usethetics/design-token-transformer/dispatches
```

I will update the readme to make this easier to understand by adding an example. 

Let me know if it works like that.

**Comment by usethetics** [comment]
Awesome, thanks, it would beautifully now!

**Comment by lukasoppermann** [comment]
Awesome. If you have any idea (apart from adding the example url to the readme) of how I can make this easier to understand, please let me know. Sometimes it is hard to write documentation for something you build yourself. 😅

**Comment by usethetics** [comment]
For me it was initially not clear that I needed to fork the transformer repo as I only wanted to see if I was able to publish tokens on GitHub and not in the transformation mindset (yet).

My main struggle was with steps three and four of the setup process:
3. Adapt the transform-tokens script in the package.json.
4. Adapt the github workflow.

Maybe explicitly mentioning that the repo URL has to be changed in step three, and that step four is optional would already clear things up a lot.

Also, I installed the repo locally with its dependencies but for the publication to Github part I don’t that is required, or is it?

On the Figma side, the server URL part might be a good one to elaborate on a bit, maybe with an example screenshot showcasing a working URL instead of the placeholder. (The placeholder would still be helpful in the Figma plugin though and it could just be me, I’m a bit of a n00b setting things like this up.)

I hope this helps, I’ll let you know if I think of anything else! 
Thanks for helping out! :-)

**Comment by lukasoppermann** [comment]
Hey, thank you for the suggestions. I guess most people are new to setting something like this up.
I had to figure it out as well, while building it. 😉 

I changed the readme a lot make it more obvious. I hope it helps.

Let me know if I missed something.

Cheers

**Comment by usethetics** [comment]
Looks great!

**Comment by davidbwaters** [comment]
The s is missing in the github url in the readme, but I'm still having trouble with this.  It's just hard to debug when it says it pushed.

**Comment by lukasoppermann** [comment]
Hey @davidbwaters do you have more info? Does it arrive at the repo? The plugin does not get any info from the repo, so it only knows if the sending worked.

You can open the console in Figma, do you see any error there?

**Comment by davidbwaters** [comment]
Hey, thanks for quick response and support.  I got it working.  Docs are much clearer now. Once I added the 's' I had to fix the event type.  

I think, depending on how simple you wanna keep things, you could simplify (for designers who don't do much api stuff) in a couple of ways. You could have a dropdown for webhooks and one for github actions.  Under the actions options, you could have user name and repo inputs and construct the url.  

Maybe hide the header option under a 'custom header' checkbox, since most people will be using this repo as a base.  Same could be done with 'custom event type'.

As far as the response goes, I haven't worked with gh actions much, but I was getting a success message even with wrong info.  I was debugging and changed my token and even got success response with the wrong token.  

I feel like there's gotta be a way to setup the actions response to check if was successful or not and you could just show the response on error.  Since it can trigger node scripts, could you run a script to check and send back it's response to check if the build worked through actions or webhooks?  Just show an http post style response on error?

If gh actions are limited, I feel like netlify or similar might make it easier to automate all of this.  They have those 'deploy to netlify' links that automatically clones a repo and sets up netlify project.
